### ISSUE TITLE
Implement transformer that fits/transforms groupwise

### ISSUE THREAD

**Issue by kelvin-lu** [HDI-Project/ballet#18]
Create a grouped transformer that fits better with a fit_transform model than the current model. 

Idea: Calculate all the values in the `fit` stage, and apply them during the `transform` stage.

**Comment by micahjsmith** [comment]
more ideas
- called `GroupwiseTransformer`
- init args include:
    - `transformer`: BaseTransformer instance, cloneable
    - `groupby_kwargs`
    - flag for what to do when new groups appear in transform stage: error, nan, passthrough, maybe more.
