### ISSUE TITLE
Potential relevance/redundancy implementations in ballet

### ISSUE THREAD

**Issue by kelvin-lu** [HDI-Project/ballet#23]
# group-SOALA
group-SOALA is a potential alternative to alpha-investing as it is potentially faster and does not rely on state for its computations (though it is useful if state is saved, it can be run from only the features currently accepted to a Ballet repository).

Brief Sketch of Implementation (starting from the current `alpha-investing` implementation where we pull out `candidate_feature` and `accepted_features`:

## Acceptance/Reject check on Travis:

Acceptance in group-SOALA is already broken down into one relevance subroutine and one redundancy subroutine.

### Relevance subroutine

Transform *only* `candidate_feature` and calculate the mutual information between `candidate_feature` and the target y using [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.mutual_info_classif.html). 
If *any* column has a non-zero information, we move on. Otherwise, we immediately reject (feature is *irrelevant*

### Redundancy subroutine

- Transform all of the `accepted_features` and calculate each columns' mutual information score w.r.t. the target column. For each accepted column `accepted_col` and each candidate column `candidate_col`, do:
  - Compare their information scores. If `accepted_col` has a higher score, calculate their mutual information. If their mutual information is higher than the mutual information between `candidate_col` and the target column, mark `candidate_col` as redundant.
- Once either all `candidate_col`'s have been marked redundant or all non-redundant columns have been checked against all `accepted_col`'s, we finish. if all columns are redundant, reject. Otherwise, we accept the feature.

## Redundancy Check on Travis.

On merge, we begin a pruning subroutine on Travis CI. This entails running the redundancy subroutine on each feature, deleting the feature entirely if it is found to be redundant.

**Comment by micahjsmith** [comment]
this seems very promising

**Comment by kelvin-lu** [comment]
# GFSSF
GFSSF is also a promising alternative to alpha-investing, as it requires no state besides the currently accepted features. Furthermore, it **penalizes large group features** by setting the requirement for relevance and redundancy to be a function of the feature columns.

Unfortunately, it relies heavily on conditional mutual information, which is not implemented by sklearn and there don't seem to be tools to calculate entropy on *continuous* distributions, which would be necessary to implement an information routine. Here is a brief sketch of a **modified** routine that is better able to fit our needs. 

## Acceptance/Relevance Routine

Acceptance and Relevance are broken down into two large subsections: **within** the candidate feature (inGFSSF) and **total relevance** (a part of agGFSSF). At this time, we only transform `candidate-feature`.

### inGFSSF (intra-feature relevance)

I propose that we use group-SOALA's for this section, as the original algorithm relies heavily on conditional mutual information. Here, fore each column `candidate_col`, check whether or not the mutual information with the target column is **non-zero**. If it isn't, reject this column as a *irrelevant* feature. 

Once we have only relevant columns, we will also check for redundant columns. For each two columns `x,y` such that x is more relevant to the target, check their mutual information. If there is more information between x and y than there is between y and the target, reject `y` as a *redundant* feature.

Once we gather all of this information, if there are still columns that have not been rejected, we will continue. 

### agGFSSF (total relevance).

At this point, we have a subset of our original feature columns. We calculate this feature matrix's information with the target column, and compare it against `lambda_1 + lambda_2 * len(candidate_features)`. If the information is lower, we reject the new feature group as being **overall irrelevant**.  Here, we can use `lambda_1 = lambda_2 = entropy(target_column) / 4`

**Comment by micahjsmith** [comment]
Closed by #28 and #38
